name: Build on container image

on:
  push:
    branches: 
      - master


jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
    - name: "Get webapp's container version"
      run: |
        # version=(az webapp get-container-version)
        # export CONTAINER_VERSION=version

  build-and-test:
    needs: set-env
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/appsvc/python

    steps:
    - uses: actions/checkout@v2

    - name: Create and start virtual environment # (specifically named "antenv")
      run: |
        python3 -m venv antenv
        . antenv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'freeberg-django-container-build'
        publish-profile: ${{ secrets.CONTAINER_BUILD_SITE_PUB_PROFILE }}
